// Generated by src/generate-spec-java.js 

/**
 * Copyright 2015 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.shapesecurity.shift.ast;

import org.jetbrains.annotations.NotNull;
import com.shapesecurity.functional.data.HashCodeBuilder;

public class BindingIdentifier extends Node implements BindingIdentifierMemberExpression, Binding
{

  @NotNull
  public final String name;

  public BindingIdentifier (@NotNull SourceSpan loc, @NotNull String name)
  {
    super(loc);
    this.name = name;
  }

  public BindingIdentifier (@NotNull String name)
  {
    super();
    this.name = name;
  }

  @Override
  public boolean equals(Object object)
  {
    return object instanceof BindingIdentifier && this.name.equals(((BindingIdentifier) object).name);
  }

  @Override
  public int hashCode()
  {
    int code = HashCodeBuilder.put(0, "BindingIdentifier");
    code = HashCodeBuilder.put(code, this.name);
    return code;
  }

  @NotNull
  public String getName()
  {
    return this.name;
  }

  @NotNull
  public BindingIdentifier setName(@NotNull String name)
  {
    return new BindingIdentifier(name);
  }

}