// Generated by src/generate-spec-java.js 

/*
 * Copyright 2015 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.shapesecurity.shift.ast;

import com.shapesecurity.functional.data.HashCodeBuilder;
import com.shapesecurity.shift.ast.operators.Precedence;

import org.jetbrains.annotations.NotNull;

public class ComputedMemberExpression extends MemberExpression implements Node {

    @NotNull
    public final Expression expression;

    @NotNull
    public final ExpressionSuper _object;

    public ComputedMemberExpression(@NotNull Expression expression, @NotNull ExpressionSuper _object) {
        super(_object);
        this.expression = expression;
        this._object = _object;
    }

    @Override
    public boolean equals(Object object) {
        return object instanceof ComputedMemberExpression && this.expression.equals(
            ((ComputedMemberExpression) object).expression) && this._object.equals(
            ((ComputedMemberExpression) object)._object);
    }

    @Override
    public int hashCode() {
        int code = HashCodeBuilder.put(0, "ComputedMemberExpression");
        code = HashCodeBuilder.put(code, this.expression);
        code = HashCodeBuilder.put(code, this._object);
        return code;
    }

    @NotNull
    public Expression getExpression() {
        return this.expression;
    }

    @NotNull
    public ComputedMemberExpression setExpression(@NotNull Expression expression) {
        return new ComputedMemberExpression(expression, this._object);
    }

    @NotNull
    public ExpressionSuper get_object() {
        return this._object;
    }

    @NotNull
    public ComputedMemberExpression set_object(@NotNull ExpressionSuper _object) {
        return new ComputedMemberExpression(this.expression, _object);
    }

    @Override
    @NotNull
    public Precedence getPrecedence() {
        Precedence p = this._object.getPrecedence();
        if (p == Precedence.CALL) {
            return Precedence.CALL;
        }
        return Precedence.MEMBER;
    }

}