// Generated by src/generate-spec-java.js 

/**
 * Copyright 2015 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.shapesecurity.shift.ast;

import org.jetbrains.annotations.NotNull;
import com.shapesecurity.functional.data.HashCodeBuilder;

public class FunctionDeclaration extends Statement implements FunctionDeclarationClassDeclarationVariableDeclaration, FunctionDeclarationClassDeclarationExpression, Function
{

  @NotNull
  public final BindingIdentifier name;

  @NotNull
  public final Boolean isGenerator;

  @NotNull
  public final FormalParameters params;

  @NotNull
  public final FunctionBody body;

  public FunctionDeclaration (@NotNull BindingIdentifier name, @NotNull Boolean isGenerator, @NotNull FormalParameters params, @NotNull FunctionBody body)
  {
    super();
    this.name = name;
    this.isGenerator = isGenerator;
    this.params = params;
    this.body = body;
  }

  @Override
  public boolean equals(Object object)
  {
    return object instanceof FunctionDeclaration && this.name.equals(((FunctionDeclaration) object).name) && this.isGenerator.equals(((FunctionDeclaration) object).isGenerator) && this.params.equals(((FunctionDeclaration) object).params) && this.body.equals(((FunctionDeclaration) object).body);
  }

  @Override
  public int hashCode()
  {
    int code = HashCodeBuilder.put(0, "FunctionDeclaration");
    code = HashCodeBuilder.put(code, this.name);
    code = HashCodeBuilder.put(code, this.isGenerator);
    code = HashCodeBuilder.put(code, this.params);
    code = HashCodeBuilder.put(code, this.body);
    return code;
  }

  @NotNull
  public BindingIdentifier getName()
  {
    return this.name;
  }

  @NotNull
  public Boolean getIsGenerator()
  {
    return this.isGenerator;
  }

  @NotNull
  public FormalParameters getParams()
  {
    return this.params;
  }

  @NotNull
  public FunctionBody getBody()
  {
    return this.body;
  }

  @NotNull
  public FunctionDeclaration setName(@NotNull BindingIdentifier name)
  {
    return new FunctionDeclaration(name, this.isGenerator, this.params, this.body);
  }

  @NotNull
  public FunctionDeclaration setIsGenerator(@NotNull Boolean isGenerator)
  {
    return new FunctionDeclaration(this.name, isGenerator, this.params, this.body);
  }

  @NotNull
  public FunctionDeclaration setParams(@NotNull FormalParameters params)
  {
    return new FunctionDeclaration(this.name, this.isGenerator, params, this.body);
  }

  @NotNull
  public FunctionDeclaration setBody(@NotNull FunctionBody body)
  {
    return new FunctionDeclaration(this.name, this.isGenerator, this.params, body);
  }

}