// Generated by src/generate-spec-java.js 

/**
 * Copyright 2015 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.shapesecurity.shift.ast;

import org.jetbrains.annotations.NotNull;
import com.shapesecurity.functional.data.HashCodeBuilder;
import com.shapesecurity.functional.data.Maybe;

public class ImportNamespace extends ImportDeclaration
{

  @NotNull
  public final Maybe<BindingIdentifier> defaultBinding;

  @NotNull
  public final BindingIdentifier namespaceBinding;

  @NotNull
  public final String  moduleSpecifier;

  public ImportNamespace (@NotNull Maybe<BindingIdentifier> defaultBinding, @NotNull BindingIdentifier namespaceBinding, @NotNull String  moduleSpecifier)
  {
    super(moduleSpecifier);
    this.defaultBinding = defaultBinding;
    this.namespaceBinding = namespaceBinding;
    this.moduleSpecifier = moduleSpecifier;
  }

  @NotNull
  public Maybe<BindingIdentifier> getDefaultBinding()
  {
    return this.defaultBinding;
  }

  @NotNull
  public BindingIdentifier getNamespaceBinding()
  {
    return this.namespaceBinding;
  }

  @NotNull
  public String  getModuleSpecifier()
  {
    return this.moduleSpecifier;
  }

  @NotNull
  public ImportNamespace setDefaultBinding(@NotNull Maybe<BindingIdentifier> defaultBinding)
  {
    return new ImportNamespace(defaultBinding, this.namespaceBinding, this.moduleSpecifier);
  }

  @NotNull
  public ImportNamespace setNamespaceBinding(@NotNull BindingIdentifier namespaceBinding)
  {
    return new ImportNamespace(this.defaultBinding, namespaceBinding, this.moduleSpecifier);
  }

  @NotNull
  public ImportNamespace setModuleSpecifier(@NotNull String  moduleSpecifier)
  {
    return new ImportNamespace(this.defaultBinding, this.namespaceBinding, moduleSpecifier);
  }

}