// Generated by src/generate-spec-java.js 

/**
 * Copyright 2015 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.shapesecurity.shift.ast;

import org.jetbrains.annotations.NotNull;
import com.shapesecurity.functional.data.HashCodeBuilder;
import com.shapesecurity.functional.data.Maybe;

public abstract class Node
{

  @NotNull
  public final Maybe<SourceSpan> loc;

  public Node (@NotNull SourceSpan loc)
  {
    super();

    this.loc = Maybe.just(loc);
  }

  public Node ()
  {
    super();

    this.loc = Maybe.nothing();
  }

  @Override
  public boolean equals(Object object)
  {
    return object instanceof Node && this.loc.equals(((Node) object).loc);
  }

  @Override
  public int hashCode()
  {
    int code = HashCodeBuilder.put(0, "Node");
    code = HashCodeBuilder.put(code, this.loc);
    return code;
  }

  @NotNull
  public Maybe<SourceSpan> getLoc()
  {
    return this.loc;
  }

}