// Generated by src/generate-spec-java.js 

/*
 * Copyright 2015 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.shapesecurity.shift.ast;

import org.jetbrains.annotations.NotNull;
import com.shapesecurity.functional.data.HashCodeBuilder;

public class Setter extends MethodDefinition implements Node {

  @NotNull
  public final Parameter param;

  @NotNull
  public final FunctionBody body;

  @NotNull
  public final PropertyName name;

  public Setter (@NotNull Parameter param, @NotNull FunctionBody body, @NotNull PropertyName name)
  {
    super(body, name);
    this.param = param;
    this.body = body;
    this.name = name;
  }

  @Override
  public boolean equals(Object object)
  {
    return object instanceof Setter && this.param.equals(((Setter) object).param) && this.body.equals(((Setter) object).body) && this.name.equals(((Setter) object).name);
  }

  @Override
  public int hashCode()
  {
    int code = HashCodeBuilder.put(0, "Setter");
    code = HashCodeBuilder.put(code, this.param);
    code = HashCodeBuilder.put(code, this.body);
    code = HashCodeBuilder.put(code, this.name);
    return code;
  }

  @NotNull
  public Parameter getParam()
  {
    return this.param;
  }

  @NotNull
  public FunctionBody getBody()
  {
    return this.body;
  }

  @NotNull
  public PropertyName getName()
  {
    return this.name;
  }

  @NotNull
  public Setter setParam(@NotNull Parameter param)
  {
    return new Setter(param, this.body, this.name);
  }

  @NotNull
  public Setter setBody(@NotNull FunctionBody body)
  {
    return new Setter(this.param, body, this.name);
  }

  @NotNull
  public Setter setName(@NotNull PropertyName name)
  {
    return new Setter(this.param, this.body, name);
  }

}