// Generated by src/generate-spec-java.js 

/**
 * Copyright 2015 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.shapesecurity.shift.ast;

import org.jetbrains.annotations.NotNull;
import com.shapesecurity.functional.data.HashCodeBuilder;
import com.shapesecurity.functional.data.Maybe;

public class SourceSpan
{

  @NotNull
  public final Maybe<String> source;

  @NotNull
  public final SourceLocation start;

  @NotNull
  public final SourceLocation end;

  public SourceSpan (@NotNull Maybe<String> source, @NotNull SourceLocation start, @NotNull SourceLocation end)
  {
    super();
    this.source = source;
    this.start = start;
    this.end = end;
  }

  @Override
  public boolean equals(Object object)
  {
    return object instanceof SourceSpan && this.source.equals(((SourceSpan) object).source) && this.start.equals(((SourceSpan) object).start) && this.end.equals(((SourceSpan) object).end);
  }

  @Override
  public int hashCode()
  {
    int code = HashCodeBuilder.put(0, "SourceSpan");
    code = HashCodeBuilder.put(code, this.source);
    code = HashCodeBuilder.put(code, this.start);
    code = HashCodeBuilder.put(code, this.end);
    return code;
  }

  @NotNull
  public Maybe<String> getSource()
  {
    return this.source;
  }

  @NotNull
  public SourceLocation getStart()
  {
    return this.start;
  }

  @NotNull
  public SourceLocation getEnd()
  {
    return this.end;
  }

  @NotNull
  public SourceSpan setSource(@NotNull Maybe<String> source)
  {
    return new SourceSpan(source, this.start, this.end);
  }

  @NotNull
  public SourceSpan setStart(@NotNull SourceLocation start)
  {
    return new SourceSpan(this.source, start, this.end);
  }

  @NotNull
  public SourceSpan setEnd(@NotNull SourceLocation end)
  {
    return new SourceSpan(this.source, this.start, end);
  }

}