// Generated by src/generate-spec-java.js 

/*
 * Copyright 2015 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.shapesecurity.shift.ast;

import org.jetbrains.annotations.NotNull;
import com.shapesecurity.functional.data.HashCodeBuilder;
import com.shapesecurity.functional.data.ImmutableList;

public class VariableDeclaration implements Node, FunctionDeclarationClassDeclarationVariableDeclaration, VariableDeclarationAssignmentTarget, VariableDeclarationExpression {

  @NotNull
  public final VariableDeclarationKind kind;

  @NotNull
  public final ImmutableList<VariableDeclarator> declarators;

  public VariableDeclaration (@NotNull VariableDeclarationKind kind, @NotNull ImmutableList<VariableDeclarator> declarators)
  {
    super();
    this.kind = kind;
    this.declarators = declarators;
  }

  @Override
  public boolean equals(Object object)
  {
    return object instanceof VariableDeclaration && this.kind.equals(((VariableDeclaration) object).kind) && this.declarators.equals(((VariableDeclaration) object).declarators);
  }

  @Override
  public int hashCode()
  {
    int code = HashCodeBuilder.put(0, "VariableDeclaration");
    code = HashCodeBuilder.put(code, this.kind);
    code = HashCodeBuilder.put(code, this.declarators);
    return code;
  }

  @NotNull
  public VariableDeclarationKind getKind()
  {
    return this.kind;
  }

  @NotNull
  public ImmutableList<VariableDeclarator> getDeclarators()
  {
    return this.declarators;
  }

  @NotNull
  public VariableDeclaration setKind(@NotNull VariableDeclarationKind kind)
  {
    return new VariableDeclaration(kind, this.declarators);
  }

  @NotNull
  public VariableDeclaration setDeclarators(@NotNull ImmutableList<VariableDeclarator> declarators)
  {
    return new VariableDeclaration(this.kind, declarators);
  }

}