// Generated by src/generate-spec-java.js 

/**
 * Copyright 2015 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.shapesecurity.shift.ast;

import org.jetbrains.annotations.NotNull;
import com.shapesecurity.functional.data.HashCodeBuilder;
import com.shapesecurity.functional.data.Maybe;

public class VariableDeclarator extends Node
{

  @NotNull
  public final Binding binding;

  @NotNull
  public final Maybe<Expression> init;

  public VariableDeclarator (@NotNull SourceSpan loc, @NotNull Binding binding, @NotNull Maybe<Expression> init)
  {
    super(loc);
    this.binding = binding;
    this.init = init;
  }

  public VariableDeclarator (@NotNull Binding binding, @NotNull Maybe<Expression> init)
  {
    super();
    this.binding = binding;
    this.init = init;
  }

  @NotNull
  public Binding getBinding()
  {
    return this.binding;
  }

  @NotNull
  public Maybe<Expression> getInit()
  {
    return this.init;
  }

  @NotNull
  public VariableDeclarator setBinding(@NotNull Binding binding)
  {
    return new VariableDeclarator(binding, this.init);
  }

  @NotNull
  public VariableDeclarator setInit(@NotNull Maybe<Expression> init)
  {
    return new VariableDeclarator(this.binding, init);
  }

}