// Generated by ast.js
/**
 * Copyright 2018 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.shapesecurity.shift.es2017.ast;

import javax.annotation.Nonnull;
import com.shapesecurity.functional.data.HashCodeBuilder;
import com.shapesecurity.functional.data.Maybe;

public class ForStatement extends IterationStatement {
    @Nonnull
    public final Maybe<VariableDeclarationExpression> init;

    @Nonnull
    public final Maybe<Expression> test;

    @Nonnull
    public final Maybe<Expression> update;


    public ForStatement (@Nonnull Maybe<VariableDeclarationExpression> init, @Nonnull Maybe<Expression> test, @Nonnull Maybe<Expression> update, @Nonnull Statement body) {
        super(body);
        this.init = init;
        this.test = test;
        this.update = update;
    }


    @Override
    public boolean equals(Object object) {
        return object instanceof ForStatement && this.init.equals(((ForStatement) object).init) && this.test.equals(((ForStatement) object).test) && this.update.equals(((ForStatement) object).update) && this.body.equals(((ForStatement) object).body);
    }


    @Override
    public int hashCode() {
        int code = HashCodeBuilder.put(0, "ForStatement");
        code = HashCodeBuilder.put(code, this.init);
        code = HashCodeBuilder.put(code, this.test);
        code = HashCodeBuilder.put(code, this.update);
        code = HashCodeBuilder.put(code, this.body);
        return code;
    }

}
