// Generated by ast.js
/**
 * Copyright 2018 Shape Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.shapesecurity.shift.es2017.ast;

import javax.annotation.Nonnull;
import com.shapesecurity.functional.data.HashCodeBuilder;
import com.shapesecurity.shift.es2017.ast.operators.Precedence;

public class IdentifierExpression extends VariableReference implements Expression {


    public IdentifierExpression (@Nonnull String name) {
        super(name);
    }


    @Override
    public boolean equals(Object object) {
        return object instanceof IdentifierExpression && this.name.equals(((IdentifierExpression) object).name);
    }


    @Override
    public int hashCode() {
        int code = HashCodeBuilder.put(0, "IdentifierExpression");
        code = HashCodeBuilder.put(code, this.name);
        return code;
    }

    @Override
    @Nonnull
    public Precedence getPrecedence() {
        return Precedence.PRIMARY;
    }

}
